model: claude:claude-sonnet-4-6
temperature: null
top_p: null
max_output_tokens: 4096

save: true
save_session: null
highlight: true
keybindings: emacs

clients:
  - type: claude
    models:
      - name: claude-opus-4-7
        max_input_tokens: 200000
        max_output_tokens: 32000
        require_max_tokens: true
        supports_function_calling: true
        supports_vision: true
      - name: claude-sonnet-4-6
        max_input_tokens: 200000
        max_output_tokens: 64000
        require_max_tokens: true
        supports_function_calling: true
        supports_vision: true
      - name: claude-haiku-4-5
        max_input_tokens: 200000
        max_output_tokens: 16000
        require_max_tokens: true
        supports_function_calling: true
        supports_vision: true
